### ISSUE TITLE
 Основы Ruby on Rails, часть II, урок 4-5

### ISSUE THREAD

**Issue by igorsimdyanov** [Oceannin/Study#32]
Важно запускать приложение и убеждаться, что оно работает, не просто поднимается, а что мы можем ходить по страницам.

Я не смог его запустить, так как при запуске, у меня возникает следующая ошибка

```
/Users/igorsimdyanov/www/test.dev/dz_ror/v.biketov/Study/part_5/lesson_1/todo/app/controllers/application_controller.rb:15: syntax error, unexpected end-of-input, expecting `end'
```

Это ошибка говорит, что в файле app/controllers/application_controller.rb на 15 строке, что-то не в порядке. А именно, что ruby-интерпретатор не может найти закрывающего end. Вот этот файл

```ruby
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  before_action :devise_permit_params, if: :devise_controller?
  before_action :check_locale
  private

  def check_locale
    I18n.locale = session[:locale] if I18n.available_locale.include? session[:locale]&.to_sym

  def devise_permit_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end
```

Важно такие ошибки устранять, иначе приложение не будет работать. Прямо надо сесть и разобраться. Например так: мы комментируем все содержимое этого файла кроме class и соответствующего ему end

```ruby
# frozen_string_literal: true

sclass ApplicationController < ActionController::Base
  # include Pundit
  # before_action :devise_permit_params, if: :devise_controller?
  # before_action :check_locale
  # private

  # def check_locale
  #   I18n.locale = session[:locale] if I18n.available_locale.include? session[:locale]&.to_sym

  # def devise_permit_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end
```

По крайней мере эта ошибка исчезает. Осторожно снимаем комментарии, учитывая, что колбэки обращаются в методам, определенным после private

```ruby
# frozen_string_literal: true

sclass ApplicationController < ActionController::Base
  # include Pundit
  # before_action :devise_permit_params, if: :devise_controller?
  # before_action :check_locale
  # private

  # def check_locale
  #   I18n.locale = session[:locale] if I18n.available_locale.include? session[:locale]&.to_sym

  # def devise_permit_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end
```

Вот так работает

```ruby
class ApplicationController < ActionController::Base
  include Pundit
  before_action :devise_permit_params, if: :devise_controller?
  # before_action :check_locale
  private

  # def check_locale
  #   I18n.locale = session[:locale] if I18n.available_locale.include? session[:locale]&.to_sym

  def devise_permit_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end
```

Значит дело в check_locale и в самом деле видно, что у него не хватает завершающего end, о чем нам сообщал ruby-интерпрератор. Таак как он не мог уже восстановить структуру вложения - он указал на конец файла, что он там сломался. На самом деле он сломался выше в районе метода check_locale. Искусства программирования заключается в том, чтобы вычислить где ошибка. Снимаем комментарии и добавляем не достающий end.

```ruby
class ApplicationController < ActionController::Base
  include Pundit
  before_action :devise_permit_params, if: :devise_controller?
  before_action :check_locale
  private

  def check_locale
    I18n.locale = session[:locale] if I18n.available_locale.include? session[:locale]&.to_sym
  end

  def devise_permit_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end
```

Так, теперь возникает другая ошибка: undefined method `available_locale' for I18n:Module. Причем Ruby-итерпретатор сразу же подсказывает, что есть похожий метод, но в котором слово locale во множественном числе

```ruby
NoMethodError (undefined method `available_locale' for I18n:Module
Did you mean?  available_locales
               available_locales=):
```

Пробуем available_locale заменить на available_locales.

Так, эта ошибка исчезла. Теперь другая

```ruby
ActionView::Template::Error (undefined local variable or method `toggle_path' for #<ActionView::Base:0x0000000000abb8>):
    1: - link_name = session[:locale] == I18n.default_locale.to_s ? 'EN' : 'RU'
    2: =< link_to link_name, toggle_path, method: :post
```

Нет такого метода toggle_path. Смотрим список роутов при помощи команды `rails routes -g toggle`. В самом деле такого роута нет, а следовательно и RoR не подготовит подходящий path-хэлпер. Предлагаю пока эту строку закомментировать. Идем в app/views/shared/_language_switch.html.slim и все в файле комментируем

```ruby
/ - link_name = session[:locale] == I18n.default_locale.to_s ? 'EN' : 'RU'
/ =< link_to link_name, toggle_path, method: :post
```

По крайней мере теперь страница запускается. Так следует поступать с каждой ошибкой, не должно быть такого, что вы что-то делаете и не проверяете - работает оно после этого или нет. Потому что он с высокой долей вероятности сломается и нужно прикладывать усилия, чтобы поддерживать его в работоспособном состоянии.

**Comment by Oceannin** [comment]
Спасибо, все поправил, постараюсь лучше
